# Day 3 - NumPy Fundamentals

## Objectives
- Introduction to NumPy
- Creating Arrays
- Array Attributes
- Indexing & Slicing
- Mathematical Operations
- Statistical Functions
- Practical Examples

In [4]:
import numpy as np

In [6]:
print("Numpy Version:", np.__version__)

Numpy Version: 2.5.1


In [11]:
#1D Array
arr1 = np.array([10,20,30,40,50])

#2D Array
arr2 = np.array([
    [1,2,3],
    [4,5,6]
])

print(f"1D Array: {arr1}")
print(f"2D Array: {arr2}")

1D Array: [10 20 30 40 50]
2D Array: [[1 2 3]
 [4 5 6]]


In [14]:
#Array properties
print("Shape : ",arr2.shape)
print("size : ",arr2.size)
print("Dimension : ",arr2.ndim)
print("DAta type : ",arr2.dtype)

Shape :  (2, 3)
size :  6
Dimension :  2
DAta type :  int64


In [15]:
#Special Arrays
zeros = np.zeros((3,3))
print("Zeros Array:\n",zeros)

ones = np.ones((2,4))
print("Ones Array:\n",ones)

identity = np.eye(4)
print("Identity Matrix:\n",identity)

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
#Array Indexing and Slicing
numbers = np.array([10,20,30,40,50,60,70,80])
print("Original Array:", numbers)

print("\nElement at index 1:", numbers[1])
print("\nElement at index -1:", numbers[-1])
print("\nElement at index 5:", numbers[5])

print("\nElement at index 2 to 5:", numbers[2:5])
print("\nElement at index 0 to 5 with step 2:", numbers[0:5:2])
print("\nElement at index 3 to end:", numbers[3:])
print("\nElement at index 0 to 8 in reverse:", numbers[::-1])



Original Array: [10 20 30 40 50 60 70 80]

Element at index 1: 20

Element at index -1: 80

Element at index 5: 60

Element at index 2 to 5: [30 40 50]

Element at index 0 to 5 with step 2: [10 30 50]

Element at index 3 to end: [40 50 60 70 80]

Element at index 0 to 8 in reverse: [80 70 60 50 40 30 20 10]


In [21]:
#Arithematic Operations

a = np.array([10,20,30])
b = np.array([2,4,6])

print("Addition:", a+b)
print("Subtraction:", a-b)
print("Multiplication:", a*b)
print("Division:", a/b)

Addition: [12 24 36]
Subtraction: [ 8 16 24]
Multiplication: [ 20  80 180]
Division: [5. 5. 5.]


In [ ]:
#Mathematical Functions

num = np.array([4,9,16,25,36])

print("Square Root :",np.sqrt(num))
print("square :",np.square(num))
print("Exponential :",np.exp(num))
print("Logarithm :",np.log(num))




Square Root : [2. 3. 4. 5. 6.]
square : [  16   81  256  625 1296]
Exponential : [5.45981500e+01 8.10308393e+03 8.88611052e+06 7.20048993e+10
 4.31123155e+15]
Logarithm : [1.38629436 2.19722458 2.77258872 3.21887582 3.58351894]


In [22]:
#Statistical Functions

marks = np.array([85, 92, 78, 90, 88])
print("mean :", np.mean(marks))
print("median :", np.median(marks))
print("standard deviation :", np.std(marks))
print("maximum :", np.max(marks))

mean : 86.6
median : 88.0
standard deviation : 4.882622246293481
maximum : 92


In [24]:
#Reshaping arrays

arr = np.array([1, 2, 3, 4, 5])

print("original array:", arr)
print("Reshaped array :\n", arr.reshape(5,1))

original array: [1 2 3 4 5]
Reshaped array :
 [[1]
 [2]
 [3]
 [4]
 [5]]


In [30]:
#Random Numbers

np.random.seed(42)
random_numbers = np.random.randint(1,100,size = 10)
print("Random numbers from 1 to 100:", random_numbers)

Random numbers from 1 to 100: [52 93 15 72 61 21 83 87 75 75]


In [31]:
#Mini Practice Problem (Student Scores)
scores = np.array([78, 85, 92, 88, 76, 95, 89, 84, 91, 87])

print("Scores:", scores)
print("Average score:", np.mean(scores))
print("Highest score:", np.max(scores))
print("Lowest score:", np.min(scores))

passed  = scores[scores >= 60]
print("Students scoring above 60:", passed)
print("Number of students scoring above 60:", len(passed))

Scores: [78 85 92 88 76 95 89 84 91 87]
Average score: 86.5
Highest score: 95
Lowest score: 76
Students scoring above 60: [78 85 92 88 76 95 89 84 91 87]
Number of students scoring above 60: 10


In [34]:
#Challenge problem

study_hrs = np.array([2,3,4,5,6])
scores = np.array([70, 75, 80, 85, 90])

improvement = scores - scores[0]

print("study hours : ", study_hrs)
print("scores : ", scores)
print("Improvement : ", improvement)
print("Average Scores : ", np.mean(scores))

study hours :  [2 3 4 5 6]
scores :  [70 75 80 85 90]
Improvement :  [ 0  5 10 15 20]
Average Scores :  80.0
